Develop
Jariodson/java-filmorate pull request #20
Opened 2024-04-11 19:29 UTC by Jariodson

2024-04-13 08:32 UTC, swwwer82 commented
my comment

2024-04-13 08:32 UTC, Gmilovidov commented
Check

2024-04-13 14:33 UTC, dgumich requested changes

2024-04-13 14:33 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    private int useful;
Надо приходить к единообразию в коде. Если используете объекты, то используйте их во всех полях. Поменяйте int на Integer

2024-04-13 14:33 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
>      private String email;
На самом деле просто аннотации @Email недостаточно, так как она не обрабатывает один кейс. Какой - можете проверить в документации к ней=)

2024-04-13 14:33 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/model/UserFeed.java
> +    Long eventId;
А поля почему не приватне?

2024-04-13 14:33 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/RecommendationsServiceImpl.java
> +    Map<User, ArrayList<Film>> data;
Поле должно быть приватным. Но вообще этого поля не должно быть. Мапа используется в методе getRecommendations так что должна быть там, а не на уровне класса.

2024-04-13 14:33 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/ReviewServiceImpl.java
> +            review = reviewDao.getReviewById(id);
Можно просто в блоке трай записать return reviewDao.getReviewById(id);, тогда не не нужны будут строки 72 и 78

2024-04-13 14:33 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/storage/dal/dao/FilmDbStorage.java
> +        FilmParameter sortTypes = FilmParameter.validateFilmParameter(filmSearchParameter);
Эту логику надо вынести в сервис. Мы же исходя из типа сортировки вызываем нужный метод стореджа.

2024-04-13 14:33 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/storage/dal/DirectorDal.java
> +public interface DirectorDal {
Странное название для интерфейса DirectorDal, что за дал?=) И такое же странное название пакета.

2024-04-13 14:33 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/storage/dal/dao/LikeDao.java
> +
@Autowired над конструктором. Да, без этого работает, но лучше ставить для наглядности. Тем более во всём проекте до этого ставили.

2024-04-13 16:47 UTC, iriveri commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +        log.debug("Получен запрос GET на получение списка всех режисёров");
Вроде получение запроса похоже больше на отладочную информацию. Например факт добавления это уже info

2024-04-13 16:49 UTC, iriveri commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> -        log.info("Получен запрос GET на получение списка всех фильмов");
тут по факту

2024-04-13 16:58 UTC, iriveri commented on src/main/java/ru/yandex/practicum/filmorate/storage/dal/DirectorDal.java
> +public interface DirectorDal {
А камен он не дал)

2024-04-13 17:05 UTC, iriveri commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public Collection<UserFeed> getCommonFriends(@NotNull @PathVariable(value = "id") @NotNull Long userId) {
зато не null)

2024-04-13 17:14 UTC, iriveri commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +    public Director addNewDirector(@Validated(WithoutParent.class)
Оснвной идеей тут является обработка режиссёра вне класса. Поясняю, когда мы получаем объект типа Film то нам в нём необязательно иметь имя режисёра. А вот в случае если принимаем объект Director то без имени это шляпа а не режисёр.

2024-04-13 18:20 UTC, Jariodson commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        System.out.println(newReview);
вы это не видели и я тоже

2024-04-13 18:21 UTC, Jariodson commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public ResponseEntity<Review> deleteReview(@PathVariable Optional<Long> id) {
исправил

2024-04-13 18:26 UTC, Jariodson commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        long id = Long.parseLong(filmId);
исправил

2024-04-13 18:37 UTC, Jariodson commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        if (id > 0) {
исправил

2024-04-14 07:24 UTC, iriveri commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +    public void deleteDirector(@NotNull @PathVariable Long id) {
Исправлено

2024-04-14 07:25 UTC, iriveri commented on src/main/java/ru/yandex/practicum/filmorate/controller/RecommendationsController.java
> +    public Collection<Film> getUserRecommendations(@PathVariable Optional<Long> id) {
Логика теперь везде одинаковая и  Optional используется только в required=false случаях

2024-04-14 07:25 UTC, iriveri commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +
ухххх

2024-04-14 07:25 UTC, iriveri commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/RecommendationsServiceImpl.java
> +    Map<User, ArrayList<Film>> data;
Исправлено

2024-04-14 07:26 UTC, iriveri commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/ReviewServiceImpl.java
> +            review = reviewDao.getReviewById(id);
Исправлено

2024-04-14 07:27 UTC, iriveri commented on src/main/java/ru/yandex/practicum/filmorate/storage/dal/dao/FilmDbStorage.java
> +        FilmParameter sortTypes = FilmParameter.validateFilmParameter(filmSearchParameter);
Переработано

2024-04-14 07:27 UTC, iriveri commented on src/main/java/ru/yandex/practicum/filmorate/storage/dal/DirectorDal.java
> +public interface DirectorDal {
Ну теперь всё storage

2024-04-14 07:27 UTC, iriveri commented on src/main/java/ru/yandex/practicum/filmorate/storage/dal/dao/LikeDao.java
> +
Исправлено, виновные наказаны

2024-04-14 07:29 UTC, iriveri commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        throw new IllegalArgumentException("Введён неверный индефикатор фильма! Id: " + filmId);
При использовании квантового процессора и кота Шредингера в качестве аргумента (исправлено)

2024-04-14 07:29 UTC, iriveri commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        throw new IllegalArgumentException("Введён неверный индефикатор! Id: " + id + " или UserId: " + userId);
Исправлено

2024-04-14 07:29 UTC, iriveri commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public Collection<UserFeed> getCommonFriends(@NotNull @PathVariable(value = "id") @NotNull Long userId) {
Исправлено

2024-04-14 07:30 UTC, iriveri commented on src/main/java/ru/yandex/practicum/filmorate/enums/FilmParameter.java
> +    public static FilmParameter validateFilmParameter(String parameter) {
Переработано

2024-04-14 07:31 UTC, iriveri commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +    public Director addNewDirector(@Validated(WithoutParent.class)
Понял свою ошибку не до разобрался с аннотациями.  @validated выпелен

2024-04-14 07:32 UTC, iriveri commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
>      private String email;
![image](https://github.com/Jariodson/java-filmorate/assets/61321955/340bcf55-6246-4c30-9f1c-00c877c3851a)
Исправлено

2024-04-14 07:32 UTC, iriveri commented on src/main/java/ru/yandex/practicum/filmorate/model/UserFeed.java
> +    Long eventId;
теперь приватные

2024-04-15 16:51 UTC, dgumich approved these changes

2024-04-15 17:24 UTC, merged