Controllers films users
Jariodson/java-filmorate pull request #5
Opened 2024-02-05 16:42 UTC by Jariodson

2024-02-05 20:27 UTC, dgumich requested changes

2024-02-05 20:27 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.debug("Вывод всех фильмов");
debug очень низкий уровень логгирования и чаще всего он отключен. Надо использовать от info. Кроме того само сообщение не очень информативное. Что за вывод всех фильмов? Правильней будет: "Получен GET запрос на получение списка всех фильмов".

2024-02-05 20:27 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getDescription().length() > 200) {
Советую разобраться с валидацией в спринге, это позволило бы уменьшить метод валидации и проверять только дату фильма.

2024-02-05 20:27 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.debug("Добавление фильма: {}", film);
Логгирование должно быть в начале метода и в конце (еще добавляют перед тем как кидать исключение).
А то в данном случае мы можем даже не дойти до данного лога. Почему это важно? Потому что разработчик проводит много времени с разбором логов. Так что чем полнее и понятней логи, тем проще же будет работать. Кроме этого так же надо поменять уровень логирования.

2024-02-05 20:27 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    void deleteAllFilms() {
Зачем данный метод, если нигде его не используешь?

2024-02-05 20:27 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getEmail() == null || user.getEmail().isBlank()) {
Так это проверяется валидацией от спринга, зачем делать кастомную валидацию на это?

2024-02-07 18:23 UTC, Jariodson commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.debug("Вывод всех фильмов");
исправил

2024-02-07 18:23 UTC, Jariodson commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getDescription().length() > 200) {
исправил

2024-02-07 18:23 UTC, Jariodson commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.debug("Добавление фильма: {}", film);
исправил

2024-02-07 18:23 UTC, Jariodson commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    void deleteAllFilms() {
пофиксил

2024-02-07 18:23 UTC, Jariodson commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getEmail() == null || user.getEmail().isBlank()) {
пофиксил

2024-02-08 02:25 UTC, dgumich approved these changes

2024-02-08 02:25 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new ValidationException("Фильм с названием " + film.getName() + "уже добавлен");
Надо добавить пробел перед  "уже добавлен"

2024-02-08 02:25 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        log.info("Получен запрос PUT на обновление пользователя в списке");
Вот, уже лучше, но еще бы какие-нибудь данные про этого пользователя: айди или имя или еще что

2024-02-08 16:03 UTC, Jariodson commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        log.info("Получен запрос PUT на обновление пользователя в списке");
исправил

2024-02-08 21:10 UTC, merged