Add friends likes
Jariodson/java-filmorate pull request #6
Opened 2024-02-18 09:36 UTC by Jariodson

ТЗ 10

2024-02-18 16:47 UTC, dgumich requested changes

2024-02-18 16:47 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/ErrorHandler.java
> +        return new ResponseEntity<>(
Перед отправкой ответа с ошибкой хорошо бы это залогировать.

2024-02-18 16:47 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmService.getFilms();
Логирование то оставь=)

2024-02-18 16:47 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmService.addFilm(film);
Так же оставь логирование)

2024-02-18 16:47 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    FilmStorage filmStorage = new InMemoryFilmStorage();
Все, прошли внедрение зависимостей, так что забывай про создание объектов через new=) Так скоро будешь создавать только бины. Здесь нужно сделать с помощью спринга. Так же поле должно быть приватным.

2024-02-18 16:47 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        log.info("Размер списка фильмов: {}", filmStorage.getAllFilms().size());
Зачем 2 раза ходить в сторедж ради всех фильмов? Сделай локальную переменную, которой присвоишь filmStorage.getAllFilms()

2024-02-18 16:47 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (filmStorage.getFilmById(id) != null) {
Аналогично, filmStorage.getFilmById(id) присвой локальную переменную

2024-02-18 16:47 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return new ResponseEntity<>(film, HttpStatus.CREATED);
ResponseEntity<Film> уровень контроллера. На уровне сервиса ты можешь вернуть true/false/сам объект или бросить исключение.

2024-02-18 16:47 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public ResponseEntity<Film> addLike(Long filmId, Long userId) {
Аналогично, все  ResponseEntity<Film> надо вынести в контроллер, сервис должен возвращать что-то другое. В случае успеха одно, в случае провала - другое.

2024-02-18 16:47 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    UserStorage userStorage = new InMemoryUserStorage();
Аналогично, надо сделать с помощью внедрения зависимостей.

2024-02-18 16:47 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public ResponseEntity<User> createUser(User user) {
Так же надо отрефакторить сервис и вынести все ResponseEntity из него

2024-02-18 16:47 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        film.addLike(userId);
При получении фильма произойдет проверка, есть ли он вообще в "бд". А вот для пользователя такой проверки нет. Надо добавить, а то наставим лайки от несуществующих юзеров.

2024-02-18 16:47 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private void checkUserId(long id) {
А зачем нам эта проверка? В плане мы проверям только айди, что больше 0. Но она никак нас не защищает от проверки (userStorage.getUserById(id) == null) . Получается, что пользы от нее никакой: с ней мы должны проверить пользователя на null, без нее мы должны проверить пользователя на null

2024-02-18 16:47 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return user.getFriendsIds().stream()
Тут у нас может быть NPE, потому что пользователь может быть null

2024-02-18 16:47 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (userStorage.getAllUsers().stream().map(User::getId).anyMatch(id -> id.equals(userId)) &&
Не понимаю логику. Мы должны просто взять двух пользователей, проверить, что они существуют и добавить друг к другу в друзья (по аналогии как удаляешь из друзей)

2024-02-18 16:47 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        User friend = userStorage.getUserById(friendId);
Надо проверять, что пользователи не равны null

2024-02-18 16:47 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        } catch (NullPointerException e) {
Никогда так не делай=) Если ты ловишь NPE, значит, у тебя кривая логика, причем ты знаешь, что она кривая. Надо отрефакторить без NPE

2024-02-18 16:47 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        List<User> commonFriends = new ArrayList<>();
Аналогично, должны проверять пользователей, что они не null

2024-02-18 16:47 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if (film.getId() == 0) {
А это часть логики как будет работать? Вообще зачем на проверять айдишник? Понимаешь, что у мы можем прислать фильм с id=1, а потом потом создадим такой id и присвоим фильму с id=0. Что приведет к перезаписи фильма и потери первого. Логика должна быть: или мы создаем id и ответственны за то, что бы они не дублировались или мы ждем, что фильм придет с id. Сейчас сразу присутствуют обе логики. Думаю, должен быть первый вариант.

2024-02-18 16:47 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if (films.values().stream().map(Film::getName).anyMatch(film.getName()::equals)) {
Зачем проверяем название фильма? Разве не встречал фильмы с одинаковым названием, но разным годом выпуска? Или разные страны? Зачем создавать ограничения там, где их не должно быть?=)

2024-02-18 17:00 UTC, Jariodson commented on src/main/java/ru/yandex/practicum/filmorate/ErrorHandler.java
> +        return new ResponseEntity<>(
исправил

2024-02-18 17:26 UTC, Jariodson commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        log.info("Размер списка фильмов: {}", filmStorage.getAllFilms().size());
исправил

2024-02-18 17:27 UTC, Jariodson commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (filmStorage.getFilmById(id) != null) {
исправил

2024-02-18 17:27 UTC, Jariodson commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return new ResponseEntity<>(film, HttpStatus.CREATED);
исправил

2024-02-18 17:28 UTC, Jariodson commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public ResponseEntity<Film> addLike(Long filmId, Long userId) {
исправил

2024-02-18 17:28 UTC, Jariodson commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    UserStorage userStorage = new InMemoryUserStorage();
исправил

2024-02-18 17:28 UTC, Jariodson commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public ResponseEntity<User> createUser(User user) {
исправил

2024-02-18 17:36 UTC, Jariodson commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        film.addLike(userId);
исправил

2024-02-18 17:36 UTC, Jariodson commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    FilmStorage filmStorage = new InMemoryFilmStorage();
исправил

2024-02-18 17:37 UTC, Jariodson commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmService.getFilms();
исправил

2024-02-18 17:39 UTC, Jariodson commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmService.addFilm(film);
исправил

2024-02-18 17:45 UTC, Jariodson commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private void checkUserId(long id) {
исправил

2024-02-18 18:01 UTC, Jariodson commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return user.getFriendsIds().stream()
исправил

2024-02-18 18:04 UTC, Jariodson commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (userStorage.getAllUsers().stream().map(User::getId).anyMatch(id -> id.equals(userId)) &&
исправил

2024-02-18 18:12 UTC, Jariodson commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        User friend = userStorage.getUserById(friendId);
Не совсем понял. При создании пользователя идёт проверка на валидацию, где также есть проверка на null. Значит, в UserStorage точно нет user равному null. Я добавил проверку на поиск id.

2024-02-18 18:56 UTC, Jariodson commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if (film.getId() == 0) {
исправил

2024-02-18 18:56 UTC, Jariodson commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if (films.values().stream().map(Film::getName).anyMatch(film.getName()::equals)) {
исправил

2024-02-18 20:12 UTC, Jariodson commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        } catch (NullPointerException e) {
исправил

2024-02-18 20:13 UTC, Jariodson commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        List<User> commonFriends = new ArrayList<>();
тот же вопрос. Если известно, что при добавлении пользователя у нас проверка на null, то зачем проверять потом?

2024-02-19 04:15 UTC, dgumich requested changes

2024-02-19 04:15 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if (film.getId() == 0) {
Не исправил=( В чем проблема: мы прислали фильм с id=0, создали ему id=1 и положили в мапу. Следующий прислали фильм с id=1, здесь ничего не сделали. Потом проверяем и видим, что в мапе есть такой ключ-фильм. Возвращаем ошибку. Происходит раздвоение айдишников. Кто за ними следит? Мы? да, вроде бы мы следим. В то же самое время к нам могут прилететь фильмы с айди, которыми мы не управляем. А откуда там знают, какой айди можно использовать, какой нет? Поэтому и говорил, что надо удалить проверку.
Сделай как это было в задании с бордой: мы сами сетили задаче/подзадче/эпику айди во всех случаях, а не только id==0

2024-02-19 04:15 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        if (user.getId() == null) {
Аналогично, мы должны сетить айди пользователям, иначе произойдет путаница.

2024-02-19 04:15 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +        if (friendsIds == null) {
(friendsIds == null) никогда не будет, потому что поле мы сразу инициализируем ( friendsIds = new HashSet<>();)

2024-02-19 04:15 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                    if (o.getLikes() == null) {
Лучше сет с лайками инициализировать сразу. Тогда он просто будет пустой, и никаких проверок на null делать не надо

2024-02-19 04:15 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private void checkUserId(long id) {
Ответил в другом комментарии. Но дело в том, что ты просто можешь прислать айди, под которым нет пользователя/фильма. Вот и все, мапа в таком случае вернет null, вот и получим NPE

2024-02-19 08:10 UTC, Jariodson commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +@Scope("singleton")
исправил

2024-02-19 08:11 UTC, Jariodson commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +            log.warn("Фильм с названием {} уже добавлен", film.getName());
исправил

2024-02-19 08:29 UTC, Jariodson commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        if (user.getId() == null) {
исправил

2024-02-19 09:18 UTC, Jariodson commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                    if (o.getLikes() == null) {
исправил

2024-02-19 09:18 UTC, Jariodson commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +        if (friendsIds == null) {
исправил

2024-02-19 12:45 UTC, dgumich approved these changes

2024-02-19 20:32 UTC, merged